In [1]:
import pandas as pd 
 
df = pd.read_csv("SUBTLEX-US frequency list with PoS and Zipf information.csv")
df

,Word,FREQcount,CDcount,FREQlow,Cdlow,SUBTLWF,Lg10WF,SUBTLCD,Lg10CD,Dom_PoS_SUBTLEX,Freq_dom_PoS_SUBTLEX,Percentage_dom_PoS,All_PoS_SUBTLEX,All_freqs_SUBTLEX,Zipf-value
0,a,1041179,8382,976941,8380,20415.27,6.0175,99.93,3.9234,Article,993445.0,0.96,Article.Adverb.Letter.To.Noun.Preposition.Adje...,993445.33186.6441.744.257.52.5,7.309360
1,aa,87,70,6,5,1.71,1.9445,0.83,1.8513,Name,79.0,0.92,Name.Noun,79.7,3.236317
2,aaa,25,23,5,3,0.49,1.4150,0.27,1.3802,Name,20.0,0.80,Name.Noun,20.5,2.706807
3,aah,2688,634,52,37,52.71,3.4296,7.56,2.8028,Interjection,2657.0,1.00,Interjection,2657,4.721425
4,aahed,1,1,1,1,0.02,0.3010,0.01,0.3010,Verb,1.0,1.00,Verb,1,1.592864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74281,zygoma,2,2,1,1,0.04,0.4771,0.02,0.4771,Noun,2.0,1.00,Noun,2,1.768955
74282,zygomatic,5,5,5,5,0.10,0.7782,0.06,0.7782,Adjective,5.0,1.00,Adjective,5,2.069985
74283,zygote,7,5,4,3,0.14,0.9031,0.06,0.7782,Noun,4.0,0.57,Noun.Verb,4.3,2.194924
74284,zygotes,1,1,1,1,0.02,0.3010,0.01,0.3010,Noun,1.0,1.00,Noun,1,1.592864
74285,zymurgy,1,1,1,1,0.02,0.3010,0.01,0.3010,Noun,1.0,1.00,Noun,1,1.592864

In [2]:
df = df[['Word', 'FREQcount', 'CDcount', 'Lg10WF', 'Dom_PoS_SUBTLEX', 'Zipf-value']]
df

            Word  FREQcount  CDcount  Lg10WF Dom_PoS_SUBTLEX  Zipf-value
0              a    1041179     8382  6.0175         Article    7.309360
1             aa         87       70  1.9445            Name    3.236317
2            aaa         25       23  1.4150            Name    2.706807
3            aah       2688      634  3.4296    Interjection    4.721425
4          aahed          1        1  0.3010            Verb    1.592864
...          ...        ...      ...     ...             ...         ...
74281     zygoma          2        2  0.4771            Noun    1.768955
74282  zygomatic          5        5  0.7782       Adjective    2.069985
74283     zygote          7        5  0.9031            Noun    2.194924
74284    zygotes          1        1  0.3010            Noun    1.592864
74285    zymurgy          1        1  0.3010            Noun    1.592864

[74286 rows x 6 columns]

In [3]:
df[df['Word'].isna()]

      Word  FREQcount  CDcount  Lg10WF Dom_PoS_SUBTLEX  Zipf-value
42519  NaN        106       30  2.0294            Noun    3.321218
43907  NaN         27       18  1.4472       Adjective    2.738992

In [4]:
df = df.dropna(subset=['Word'])

In [5]:
print(df.shape)
print(df.dtypes)

(74284, 6)
Word                object
FREQcount            int64
CDcount              int64
Lg10WF             float64
Dom_PoS_SUBTLEX     object
Zipf-value         float64
dtype: object

In [6]:
df['Dom_PoS_SUBTLEX'].unique()

array(['Article', 'Name', 'Interjection', 'Verb', 'Noun', 'Adjective',
       'Unclassified', 'Adverb', 'Preposition', nan, 'Conjunction',
       'Determiner', 'Pronoun', 'Letter', 'Number', 'To', 'Not', 'Ex'],
      dtype=object)

In [7]:
df['Dom_PoS_SUBTLEX'].isna().sum()

np.int64(191)

In [8]:
df['Dom_PoS_SUBTLEX'] = df['Dom_PoS_SUBTLEX'].fillna('Unknown')

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\560106246.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dom_PoS_SUBTLEX'] = df['Dom_PoS_SUBTLEX'].fillna('Unknown')

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Dom_PoS_SUBTLEX'] = le.fit_transform(df['Dom_PoS_SUBTLEX'])

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\2247350504.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Dom_PoS_SUBTLEX'] = le.fit_transform(df['Dom_PoS_SUBTLEX'])

In [10]:
print(df['Dom_PoS_SUBTLEX'].unique())
print(df.dtypes)

[ 2  8  6 17 10  0 15  1 12 16  3  4 13  7 11 14  9  5]
Word                object
FREQcount            int64
CDcount              int64
Lg10WF             float64
Dom_PoS_SUBTLEX      int64
Zipf-value         float64
dtype: object

In [11]:
df['word_length'] = df['Word'].str.len()
df['confusable_letters'] = df['Word'].str.count('b') + df['Word'].str.count('p') + df['Word'].str.count('d') + df['Word'].str.count('q')

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\1057211701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['word_length'] = df['Word'].str.len()
C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\1057211701.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['confusable_letters'] = df['Word'].str.count('b') + df['Word'].str.count('p') + df['Word'].str.count('d') + df['Word'].str.count('q')

In [12]:
import pyphen
dic = pyphen.Pyphen(lang='en')

def count_syllables(Word):
    return len(dic.inserted(Word).split('-'))
df['syllable_count'] = df['Word'].apply(count_syllables)

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\1644669416.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['syllable_count'] = df['Word'].apply(count_syllables)

In [13]:
df['vowel_ratio'] = (df['Word'].str.count('a') + df['Word'].str.count('e') + df['Word'].str.count('o') + df['Word'].str.count('i') + df['Word'].str.count('u')) / df['word_length']

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\40097224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['vowel_ratio'] = (df['Word'].str.count('a') + df['Word'].str.count('e') + df['Word'].str.count('o') + df['Word'].str.count('i') + df['Word'].str.count('u')) / df['word_length']

In [14]:
df['has_silent_letter'] = df['Word'].str.contains('kn|wr|gh|mb|bt|mn').astype(int)

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\1281761488.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_silent_letter'] = df['Word'].str.contains('kn|wr|gh|mb|bt|mn').astype(int)

In [15]:
df['has_irregular_grapheme'] = df['Word'].str.contains('ough|aigh|eigh|tion|sion')

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\2437728917.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['has_irregular_grapheme'] = df['Word'].str.contains('ough|aigh|eigh|tion|sion')

In [16]:
import re

def count_consonant_clusters(word):
    if not isinstance(word, str):
        return 0
    clusters = re.findall(r'[bcdfghjklmnpqrstvwxyz]{2,}', word.lower())
    return len(clusters)

df['consonant_clusters'] = df['Word'].apply(count_consonant_clusters)

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\3866544339.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['consonant_clusters'] = df['Word'].apply(count_consonant_clusters)

In [17]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

syllable_count = scaler.fit_transform(df[['syllable_count']]).flatten()
consonant_clusters = scaler.fit_transform(df[['consonant_clusters']]).flatten()
confusable_letters = scaler.fit_transform(df[['confusable_letters']]).flatten()

df['difficulty_score'] = (
    0.30 * (syllable_count)     +
    0.25 * (consonant_clusters) +
    0.20 * df['has_irregular_grapheme']        +
    0.15 * df['has_silent_letter']              +
    0.10 * (confusable_letters)
) * 10

C:\Users\Dell\AppData\Local\Temp\ipykernel_5272\1061850351.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['difficulty_score'] = (

In [18]:
X = df[['word_length', 'syllable_count', 'confusable_letters', 
        'vowel_ratio', 'has_silent_letter', 'has_irregular_grapheme', 
        'consonant_clusters', 'Dom_PoS_SUBTLEX']]

y = df['difficulty_score']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
print(x_train.shape)
print(x_test.shape)

(59427, 8)
(14857, 8)

In [21]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [22]:
from sklearn.metrics import r2_score, mean_squared_error
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse:.4f}")
print(f"R2:  {r2:.4f}")

MSE: 0.0003
R2:  0.9996

In [23]:
importances = pd.Series(model.feature_importances_, index=X.columns)
print(importances.sort_values(ascending=False))

has_irregular_grapheme    0.275717
consonant_clusters        0.252628
word_length               0.195431
syllable_count            0.133665
has_silent_letter         0.090904
confusable_letters        0.051574
vowel_ratio               0.000054
Dom_PoS_SUBTLEX           0.000028
dtype: float64

In [24]:
def score_word(word):
    word = word.lower()
    
    length      = len(word)
    syllables   = count_syllables(word)
    confusable  = word.count('b') + word.count('p') + word.count('d') + word.count('q')
    silent    = 1 if any(p in word for p in ['kn','wr','gh','mb','bt','mn']) else 0
    irregular = 1 if any(p in word for p in ['ough','aigh','eigh','tion','sion']) else 0   
    clusters    = count_consonant_clusters(word)  # you have count_consonant_clusters function already
    
    # now normalize and combine using your formula
    syllables_norm  = syllables / 8
    clusters_norm   = clusters / 5
    confusable_norm = confusable / 4

    return(
    0.30 * (syllables_norm)     +
    0.25 * (clusters_norm) +
    0.2 * (irregular) +
    0.15 * (silent) +
    0.10 * (confusable_norm)
    ) * 10

print(score_word("through"))
print(score_word("cat"))
print(score_word("straightforward"))

4.875
0.375
6.875

In [25]:
def score_sentence(sentence):
    words = sentence.split(' ')
    return{word: score_word(word) for word in words}
    
print(score_sentence("the mitochondria are membrane bound organelles found in the cytoplasm of eukaryotic cells"))

{'the': 0.875, 'mitochondria': 2.75, 'are': 0.375, 'membrane': 3.0000000000000004, 'bound': 1.375, 'organelles': 2.125, 'found': 1.125, 'in': 0.375, 'cytoplasm': 2.4999999999999996, 'of': 0.375, 'eukaryotic': 2.375, 'cells': 0.875}

In [26]:
def score_word_model(word):
    word = word.lower()
    
    # calculate features
    length      = len(word)
    syllables   = count_syllables(word)
    confusable  = word.count('b') + word.count('p') + word.count('d') + word.count('q')
    silent      = 1 if any(p in word for p in ['kn','wr','gh','mb','bt','mn']) else 0
    irregular   = 1 if any(p in word for p in ['ough','aigh','eigh','tion','sion']) else 0
    clusters    = count_consonant_clusters(word)
    pos         = 0  # unknown POS for new words
    vowels      = sum(1 for c in word if c in 'aeiou')
    vowel_ratio = vowels / length if length > 0 else 0
    
    # build feature row in same order as X
    features = pd.DataFrame([[length, syllables, confusable, vowel_ratio,
                          silent, irregular, clusters, pos]],
                         columns=X.columns)
    
    return model.predict(features)[0]

def score_sentence_model(sentence):
    words = sentence.split()
    return {word: round(score_word_model(word), 2) for word in words}

print(score_sentence_model("the mitochondria are membrane bound organelles found in the cytoplasm of eukaryotic cells"))
print(score_word_model("the mitochondria are membrane bound organelles found in the cytoplasm of eukaryotic cells"))

{'the': np.float64(0.42), 'mitochondria': np.float64(2.08), 'are': np.float64(0.0), 'membrane': np.float64(2.5), 'bound': np.float64(0.92), 'organelles': np.float64(1.5), 'found': np.float64(0.67), 'in': np.float64(0.0), 'cytoplasm': np.float64(1.83), 'of': np.float64(0.0), 'eukaryotic': np.float64(1.75), 'cells': np.float64(0.42)}
4.629166666666668

In [27]:
print(df['syllable_count'].max())
print(df['consonant_clusters'].max())
print(df['confusable_letters'].max())

10
6
4